name: Project Report Renderer
description: Renders project reports to static HTML, CSS, and JavaScript
inputs:
  reportsPath:
    description: The path relative to the repo root where the reports are stored
    required: false
    default: _reports
  outputsPath:
    description: The path relative to the repo root where the exported site should be placed
    required: false
    default: docs
  noCommit:
    description: If set to any value, will prevent committing changes from the build
    required: false
  githubToken:
    description: The GitHub token used to request a Pages build. Required unless "noCommit" is set.
    required: false
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
