name: Integration Test

on:
  push: {branches: main}
  workflow_dispatch:

jobs:
  generate_data:
    name: Render test reports
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Render reports
        uses: ./
        with: {workingBranch: gh-pages}
